---
- name: playing ansible and git
  hosts: localhost
  connection: local
  become: yes
  tasks:
  - name: installing and starting  nginx load balancer 
    yum:
      name: nginx
      state: latest
    notify: restart httpd

      #  - name: enabling nginx 
      #    service: 
      #      name: nginx
      #      state: started
      #      enabled: yes
  - name: copying latest index.html file
    copy:
            src: /home/index.html
            dest: /var/www/html/
            

  handlers:
          - name: notifying to restart 
            service: 
             name: httpd
             state: restarted
...
