---
- hosts: all
  tasks:
  - name: installing nginx load balancer
    yum:
      name: nginx
      state: latest
  tasks:    
  - name: enbaling nginx load balancer
    service: 
      name: nginx
      #      state: present
      state: started
      enabled: yes

...
